### ISSUE TITLE
Create Github releases for every new push to main

### ISSUE THREAD

**Issue by jan-janssen** [pyiron/docker-stacks#122]
An example how to do this automatically is available here:
https://github.com/pyiron/pyiron-installer/blob/master/.github/workflows/deploy.yml#L18
The advantage is that it then is much easier to identify the status of the Github repository which went into a specific version of the Docker container. 

@mbruns91 Can you take a look at this?

**Comment by mbruns91** [comment]
I'll look into it 👍
