### ISSUE TITLE
[automation] Dependant and weekly releases

### ISSUE THREAD

**Issue by jan-janssen** [pyiron/docker-stacks#152]
With the recent pull requests https://github.com/pyiron/docker-stacks/pull/147 and https://github.com/pyiron/docker-stacks/pull/150 this repository should now be automatically updated. Dependabot opens pull requests, when new python packages are available and new software stacks are released on a weekly bases. 

ToDos: 

- [x] I just fixed the weekly release part today, so we should validate that it is automatically released next week. 
- [x] Dependabot currently only updates the `requirements.txt` file in the core of the repository to inform us about updates. But the conda environment files need to be updated manually. @niklassiemer is it possible to extend the Dependabot action to update the conda environment files as well? You did it for other repositories in the pyiron organisation so I think it should be possible here as well, the only challenge is that there are a range of different environment files with different requirements.

**Comment by jan-janssen** [comment]
The first dependabot updates: https://github.com/pyiron/docker-stacks/pull/155 and https://github.com/pyiron/docker-stacks/pull/154 worked as expected.

**Comment by niklassiemer** [comment]
The update of the environment(s) upon dependabot PRs is now working :) I tested this in #156 (and pushed two action fixing commits to main directly)

**Comment by jan-janssen** [comment]
Thanks a lot @niklassiemer - that sounds like we have a fully automated setup now. Let’s see if everything works according to our plans on Monday and then we can close this issue. 

- [] new docker images are released with the corresponding environments
- [] existing environments are tested as conda dry runs and the results are published on the GitHub pages branch 
- [] suggestions for updates are triggered by Dependabot and matched by our own bot to update the corresponding conda environments.

**Comment by jan-janssen** [comment]
Everything worked as expected.
