### ISSUE TITLE
[Infrastructure] Compatibility with the MaterialDigital Cloud

### ISSUE THREAD

**Issue by jan-janssen** [pyiron/docker-stacks#165]
When we started updating the Docker Containers, there was an issue with the old pyiron docker images not being compatible to the latest version of Jupyterhub used by the MaterialDigital Cloud. Is this issue resolved with the release of the new images? Or is there something we can do from the pyiron side to improve the compatibility?

**Comment by mbruns91** [comment]
I just poked the responsible person once more. As soon as I got an answer, I will update you here.

**Comment by mbruns91** [comment]
Finally, we pulled & installed the new images on the server @ KIT. The issue with inconsistent/ non-persistent homedirectories is resolved!
