### ISSUE TITLE
Specifying versions for the dependencies

### ISSUE THREAD

**Issue by muh-hassani** [pyiron/docker-stacks#23]
Based on the new implementation, all the dependencies are specified by the version. I have a concern and a question about this. 
Question: The versions specified are the latest versions. So why shouldn't the docker images be based on the latest versions?   
Concern: In case of any update to the dependecies, we need a bot to update the versions and start a pull-request. But then we have to check whether pyiron implementation is compatible with the latest version of the dependencies or not as well.

**Comment by jan-janssen** [comment]
One of the use cases of Docker is to have full reproducibility, by fixing the version it is easier for others to look up the versions we used. When somebody said he is using the pyiron Docker from Oct 2020 we can easily look up the LAMMPS version he was using. 
When the next LAMMPS version is no longer compatible to the current pyiron version we make sure our recipe is only updated  when we manually update it here. So anybody who might use the Dockerfile to build their own image always gets a working combination of packages. 
Finally the bot would be a nice extension, but for the moment I guess we are fine updating the images manually. Moreover while building the images I am not even so sure if we need all of them of if a smaller number of images like `pyiron/base`, `pyiron/lammps` and `pyiron/pyiron` is sufficient. 
I would suggest you do some more testing today and then you can present it in the developer meeting tomorrow to get some more feedback.
