### ISSUE TITLE
Which Docker Images do we need? 

### ISSUE THREAD

**Issue by jan-janssen** [pyiron/docker-stacks#25]
As already mentioned in https://github.com/pyiron/docker-stacks/issues/23#issuecomment-711624020 while I previously suggested to have more images I guess it should be fine to reduce the number of images: 

- `pyiron/base` - which includes - `pyiron_base` 
- `pyiron/lammps` - which is based on `pyiron/base` and additionally includes `pyiron`, `nglview` and `lammps`. 
- `pyiron/pyiron` - which is based on `pyiron/lammps` and additionally includes `sphinx` and `gpaw`. 

In addition we should include Dockerfiles for all images used on the internal server, especially the TEM and DAMASK examples.

**Comment by muh-hassani** [comment]
Yes, may be those three are sufficient. Pyiron/pyiron includes both sphinx and gpaw. So I guess there would be no need to include two additional images. But it depends on the feedback of the users. I am fine with removing the extra images.

**Comment by muh-hassani** [comment]
I will include an experimental image (including: temmeta, pyprismatic, match-series, and pyxem). But shall it be based on pyiron/base or pyiron/pyiron? In the case of later, the user have full simulation capabilities and experimental post-processing.

**Comment by jan-janssen** [comment]
Ideally the experimental part would be based on `pyiron/base` if this is not possible of if you plan to couple DAMASK and LAMMPS then `pyiron/lammps` should be sufficient. I just want to make sure that the Docker containers we build here are also the ones used in the MPIE Docker server.

**Comment by muh-hassani** [comment]
Our DAMASK example is coupled with LAMMPS, so `pyiron/lammps` would be suitable. In the experimental case, we do not have so far a simulation and experimental post-processing coupled. So in this case, `pyiron/base` would also be sufficient.

**Comment by jan-janssen** [comment]
Can you add the two Docker images for experimental and DAMASK?

**Comment by muh-hassani** [comment]
Sure, I am now in a meeting. I will add them just after the meeting.

**Comment by jan-janssen** [comment]
@muh-hassani Can you tell me which of the pyiron Docker Images you are currently using?

**Comment by muh-hassani** [comment]
@jan-janssen I use `pyiron/base`, `pyiron/md` and `pyiron/damask`. But I believe it will be good to have `pyiorn/pyiron` which included sphinx and GPAW.

**Comment by muh-hassani** [comment]
@jan-janssen I use also `pyiron/experimental`.

**Comment by muh-hassani** [comment]
@jan-janssen I have started a branch to address this issue.

**Comment by muh-hassani** [comment]
So I will remover the branch that I was working on.
