### ISSUE TITLE
[Bug] Environment issue

### ISSUE THREAD

**Issue by jan-janssen** [pyiron/docker-stacks#58]
The conda environment is not correctly initialised. On a mybinder container, which does not use a predefined docker image: 
https://github.com/matbinder/fenics-example
When I execute the following line in a jupyter notebook:
```
!env | grep CONDA
```
I get: 
```
CONDA_SHLVL=1
CONDA_EXE=/srv/conda/bin/conda
GSETTINGS_SCHEMA_DIR_CONDA_BACKUP=
CONDA_PREFIX=/srv/conda/envs/notebook
CONDA_DIR=/srv/conda
_CONDA_PYTHON_SYSCONFIGDATA_NAME=_sysconfigdata_x86_64_conda_cos6_linux_gnu
CONDA_PYTHON_EXE=/srv/conda/bin/python
_CE_CONDA=
CONDA_PROMPT_MODIFIER=(notebook) 
CONDA_BUILD_SYSROOT=/srv/conda/envs/notebook/x86_64-conda-linux-gnu/sysroot
CONDA_DEFAULT_ENV=notebook
```

When I use the Docker Image we build here and execute the same command, I get: 
```
CONDA_DIR=/opt/conda
CONDA_VERSION=4.9.2
```

Only when I activate the environment manually I get the correct output: 
```
!source activate; env | grep CONDA
```
Output: 
```
CONDA_EXE=/opt/conda/bin/conda
_CONDA_PYTHON_SYSCONFIGDATA_NAME=_sysconfigdata_x86_64_conda_cos6_linux_gnu
CONDA_PREFIX=/opt/conda
CONDA_PROMPT_MODIFIER=(base) 
_CE_CONDA=
CONDA_SHLVL=1
CONDA_DIR=/opt/conda
CONDA_PYTHON_EXE=/opt/conda/bin/python
CONDA_DEFAULT_ENV=base
CONDA_VERSION=4.9.2
CONDA_BUILD_SYSROOT=/opt/conda/x86_64-conda-linux-gnu/sysroot
```

So something is wrong with the initialisation of the environment. This should also fix the initialisation of the compilers on the conda level which is the issue in https://github.com/pyiron/docker-stacks/pull/54 which is currently addressed by installing additional compilers on the operation system level.

**Comment by jan-janssen** [comment]
Is this issue still valid after the recent updates?

**Comment by mbruns91** [comment]
Just tested this for the `pyiron/potentialsworkshop` image;
```bash
$ env | grep CONDA
CONDA_EXE=/opt/conda/bin/conda
CONDA_PREFIX=/opt/conda
GSETTINGS_SCHEMA_DIR_CONDA_BACKUP=
CONDA_PROMPT_MODIFIER=(base) 
_CE_CONDA=
CONDA_SHLVL=1
CONDA_DIR=/opt/conda
CONDA_PYTHON_EXE=/opt/conda/bin/python
CONDA_DEFAULT_ENV=base

$ source activate

$ env | grep CONDA
CONDA_EXE=/opt/conda/bin/conda
CONDA_PREFIX=/opt/conda
GSETTINGS_SCHEMA_DIR_CONDA_BACKUP=
CONDA_PROMPT_MODIFIER=(base) 
_CE_CONDA=
CONDA_SHLVL=1
CONDA_DIR=/opt/conda
CONDA_PYTHON_EXE=/opt/conda/bin/python
CONDA_DEFAULT_ENV=base
```
which looks fine to me.

**Comment by jan-janssen** [comment]
Great, thanks @mbruns91 for checking. Then we can close this issue.
