### ISSUE TITLE
pyiron continuum image

### ISSUE THREAD

**Issue by muh-hassani** [pyiron/docker-stacks#61]
As we have proceeded with the modularity of pyiron, I think it would be useful to create a pyiron/continuum image, instead of having both damask and finics as separate images, though we can wait till the fenics_job branch is merged to pyiron_contrib. If you, @jan-janssen, agree, I can work on it next week, after pyiron_contrib merge. There are several codacy issues still to be fix in fenics_job branch, I will fix them first.

**Comment by jan-janssen** [comment]
Sure, that is fine for me.
