### ISSUE TITLE
jupyterlab and nglview

### ISSUE THREAD

**Issue by muh-hassani** [pyiron/docker-stacks#68]
As you know nglview lab extension is not compatible with jupytelab3, and by default I have chosen lab to be the environment for the workshop cluster. The first solution would be to suppress the version of jupyterlab to 2.2.9 at pyiron/base or pyiron/md. 
The second way would be to change the environment to notebook rather than lab.
@jan-janssen, what do you think?

**Comment by jan-janssen** [comment]
We definitely want to use jupyterlab.
