### ISSUE TITLE
installation of sphinx=3.0.3 failed

### ISSUE THREAD

**Issue by muh-hassani** [pyiron/docker-stacks#90]
The Sphinx-dft installation failed. For now, I changed the version to 2.7.0. The error is as below: 
```
package sphinxdft-3.0.3-h62cddd8_0 requires mkl >=2021.2.0,<2022.0a0, but none of the providers can be installed
```

**Comment by jan-janssen** [comment]
Is this still the case?

**Comment by muh-hassani** [comment]
Yes, I wanted to contact Christoph about it. But I need to dig deeper to see what exactly the error is first.

**Comment by jan-janssen** [comment]
Maybe this is related to https://github.com/pyiron/pyiron_atomistics/issues/311
