### ISSUE TITLE
installation of damask requires mpi=1.0=mpich 

### ISSUE THREAD

**Issue by muh-hassani** [pyiron/docker-stacks#91]
The installation of damask requires `mpich` and subsquently `mpi=1.0=mpich`, but since `lammps=2021.05.27=*openmpi*` is installed, it can not switch to `mpich`.

**Comment by muh-hassani** [comment]
@jan-janssen, does it make any difference in the functionality and usage of pyiron_atomistics, if `lammps=2021.05.27=*mpich*` is installed?

**Comment by jan-janssen** [comment]
The string size that can be communicated via stdin for mpich is limited, therefore for interactive mode openmpi is required.

**Comment by muh-hassani** [comment]
As a temporary solution, I suggest that we use only for pyiron/continuum image `lammps=2021.05.27=*mpich*` and then try to communicate this issue with DAMASK developers, so they can also support `openmpi` built.

**Comment by muh-hassani** [comment]
Now Damask is built with `openmpi` as the mpi dependency.
